### ISSUE TITLE
Web page doesn't look as expected

### ISSUE THREAD

**Issue by yusufdeepwork** [upstash/examples#24]
When I enter https://examples-content.vercel.app/, It looks this image. (Note I've controlled extensions.)

<img width="1440" alt="image" src="https://github.com/upstash/examples/assets/57027351/487ae995-f42b-427a-b632-c7d061d3aa4b">

**Comment by fahreddinozcan** [comment]
This is the API response for the examples data, so this is not a non-expected behaviour for the existing implementation. We'll soon announce our examples/showcase page on [upstash.com/examples](https://upstash.com/examples), but meanwhile we'll make sure this endpoint is handled better.

**Comment by yusufdeepwork** [comment]
@fahreddinozcan Thanks for information and sorry my mistake. I am trying to understand the Upstash.

**Comment by fahreddinozcan** [comment]
No problem at all, thank you for drawing our attention. You can join our discord channel from [here](https://upstash.com/discord), and we can chat if you have any questions related to Upstash
